//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eReimbursement.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BudgetApplicationSoap")]
    public interface BudgetApplicationSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBudgetPackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBudgetPackage(string stationCode, int BudgetYear, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BudgetApplicationSoapChannel : eReimbursement.ServiceReference1.BudgetApplicationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BudgetApplicationSoapClient : System.ServiceModel.ClientBase<eReimbursement.ServiceReference1.BudgetApplicationSoap>, eReimbursement.ServiceReference1.BudgetApplicationSoap {
        
        public BudgetApplicationSoapClient() {
        }
        
        public BudgetApplicationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BudgetApplicationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BudgetApplicationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BudgetApplicationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetBudgetPackage(string stationCode, int BudgetYear, string token) {
            return base.Channel.GetBudgetPackage(stationCode, BudgetYear, token);
        }
    }
}
