//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional 的本地化字符串。
        /// </summary>
        internal static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string AllTotal {
            get {
                return ResourceManager.GetString("AllTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 的本地化字符串。
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        internal static string ApprovalRemark {
            get {
                return ResourceManager.GetString("ApprovalRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approval Search 的本地化字符串。
        /// </summary>
        internal static string ApprovalSearch {
            get {
                return ResourceManager.GetString("ApprovalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve 的本地化字符串。
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approved 的本地化字符串。
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the button on the left of each row to Approve or double click to view detail. 的本地化字符串。
        /// </summary>
        internal static string ApprovePageTitle {
            get {
                return ResourceManager.GetString("ApprovePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process 的本地化字符串。
        /// </summary>
        internal static string ApproveStatus {
            get {
                return ResourceManager.GetString("ApproveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Budget (Used/All) 的本地化字符串。
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Budget 的本地化字符串。
        /// </summary>
        internal static string BudgetOrNot {
            get {
                return ResourceManager.GetString("BudgetOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Budget Review 的本地化字符串。
        /// </summary>
        internal static string BudgetReview {
            get {
                return ResourceManager.GetString("BudgetReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Budget_YTD(Used/All) 的本地化字符串。
        /// </summary>
        internal static string BudgetYTD {
            get {
                return ResourceManager.GetString("BudgetYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail CC 的本地化字符串。
        /// </summary>
        internal static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail CC list 的本地化字符串。
        /// </summary>
        internal static string CCListTitle {
            get {
                return ResourceManager.GetString("CCListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Claim Type 的本地化字符串。
        /// </summary>
        internal static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        internal static string COARemark {
            get {
                return ResourceManager.GetString("COARemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string COAType {
            get {
                return ResourceManager.GetString("COAType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Center 的本地化字符串。
        /// </summary>
        internal static string CollectionStation {
            get {
                return ResourceManager.GetString("CollectionStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communication 的本地化字符串。
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company 的本地化字符串。
        /// </summary>
        internal static string CompanyExpense {
            get {
                return ResourceManager.GetString("CompanyExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance Due to Company 的本地化字符串。
        /// </summary>
        internal static string CompanyExpenseTotal {
            get {
                return ResourceManager.GetString("CompanyExpenseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance Due to Company: 的本地化字符串。
        /// </summary>
        internal static string CompanyExpenseTotalLabel {
            get {
                return ResourceManager.GetString("CompanyExpenseTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Pay 的本地化字符串。
        /// </summary>
        internal static string CompanyPay {
            get {
                return ResourceManager.GetString("CompanyPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy(Without attached files.) 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        internal static string Copy1 {
            get {
                return ResourceManager.GetString("Copy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy(With attached files.) 的本地化字符串。
        /// </summary>
        internal static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Center 的本地化字符串。
        /// </summary>
        internal static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Center: 的本地化字符串。
        /// </summary>
        internal static string CostCenter1 {
            get {
                return ResourceManager.GetString("CostCenter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Center(Latest) 的本地化字符串。
        /// </summary>
        internal static string CostCenterNew {
            get {
                return ResourceManager.GetString("CostCenterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency: 的本地化字符串。
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency 的本地化字符串。
        /// </summary>
        internal static string CurrencyColumn {
            get {
                return ResourceManager.GetString("CurrencyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Approver 的本地化字符串。
        /// </summary>
        internal static string CurrentApprover {
            get {
                return ResourceManager.GetString("CurrentApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer 的本地化字符串。
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Type 的本地化字符串。
        /// </summary>
        internal static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department: 的本地化字符串。
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string Department1 {
            get {
                return ResourceManager.GetString("Department1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dept. Budget MTD(Used/All) 的本地化字符串。
        /// </summary>
        internal static string DepartmentBudget {
            get {
                return ResourceManager.GetString("DepartmentBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dept. Budget YTD(Used/All) 的本地化字符串。
        /// </summary>
        internal static string DepartmentBudgetYTD {
            get {
                return ResourceManager.GetString("DepartmentBudgetYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail (Double Click the display List) 的本地化字符串。
        /// </summary>
        internal static string DetailTitle {
            get {
                return ResourceManager.GetString("DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draft Expense 的本地化字符串。
        /// </summary>
        internal static string DraftExpense {
            get {
                return ResourceManager.GetString("DraftExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string EffectPeriod {
            get {
                return ResourceManager.GetString("EffectPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Employee pay 的本地化字符串。
        /// </summary>
        internal static string Employeepay {
            get {
                return ResourceManager.GetString("Employeepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entertainment 的本地化字符串。
        /// </summary>
        internal static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expense Claim 的本地化字符串。
        /// </summary>
        internal static string ExpenseClaim {
            get {
                return ResourceManager.GetString("ExpenseClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expense Detail 的本地化字符串。
        /// </summary>
        internal static string ExpenseDetail {
            get {
                return ResourceManager.GetString("ExpenseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expense Item 的本地化字符串。
        /// </summary>
        internal static string ExpenseItem {
            get {
                return ResourceManager.GetString("ExpenseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expense List 的本地化字符串。
        /// </summary>
        internal static string ExpenseList {
            get {
                return ResourceManager.GetString("ExpenseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expense Type 的本地化字符串。
        /// </summary>
        internal static string ExpenseType {
            get {
                return ResourceManager.GetString("ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attached File 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attached File: 的本地化字符串。
        /// </summary>
        internal static string File1 {
            get {
                return ResourceManager.GetString("File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning 的本地化字符串。
        /// </summary>
        internal static string FileManagement {
            get {
                return ResourceManager.GetString("FileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File PostFix 的本地化字符串。
        /// </summary>
        internal static string FilePostFix {
            get {
                return ResourceManager.GetString("FilePostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin 的本地化字符串。
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Expense Apply 的本地化字符串。
        /// </summary>
        internal static string GeneralExpenseApply {
            get {
                return ResourceManager.GetString("GeneralExpenseApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Information 的本地化字符串。
        /// </summary>
        internal static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guest 的本地化字符串。
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly: 的本地化字符串。
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to view the process,double click to view detail. 的本地化字符串。
        /// </summary>
        internal static string MyClaimsTitle {
            get {
                return ResourceManager.GetString("MyClaimsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Expense 的本地化字符串。
        /// </summary>
        internal static string MyExpense {
            get {
                return ResourceManager.GetString("MyExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old Data 的本地化字符串。
        /// </summary>
        internal static string MyExpenseOld {
            get {
                return ResourceManager.GetString("MyExpenseOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New DSTN 的本地化字符串。
        /// </summary>
        internal static string NewDSTN {
            get {
                return ResourceManager.GetString("NewDSTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO# 的本地化字符串。
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Expense 的本地化字符串。
        /// </summary>
        internal static string OtherExpense {
            get {
                return ResourceManager.GetString("OtherExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer information 的本地化字符串。
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applicant 的本地化字符串。
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page size: 的本地化字符串。
        /// </summary>
        internal static string Pagesize {
            get {
                return ResourceManager.GetString("Pagesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Date 的本地化字符串。
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Type 的本地化字符串。
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Period 的本地化字符串。
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Period: 的本地化字符串。
        /// </summary>
        internal static string PeriodLabel {
            get {
                return ResourceManager.GetString("PeriodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reim 的本地化字符串。
        /// </summary>
        internal static string PersonalExpense {
            get {
                return ResourceManager.GetString("PersonalExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance Due to Employee 的本地化字符串。
        /// </summary>
        internal static string PersonalExpenseTotal {
            get {
                return ResourceManager.GetString("PersonalExpenseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balance Due to Employee: 的本地化字符串。
        /// </summary>
        internal static string PersonalExpenseTotalLabel {
            get {
                return ResourceManager.GetString("PersonalExpenseTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Person Budget MTD(Used/All) 的本地化字符串。
        /// </summary>
        internal static string PersonBudget {
            get {
                return ResourceManager.GetString("PersonBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Person Budget YTD(Used/All) 的本地化字符串。
        /// </summary>
        internal static string PersonBudgetYTD {
            get {
                return ResourceManager.GetString("PersonBudgetYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applicant: 的本地化字符串。
        /// </summary>
        internal static string PersonLabel {
            get {
                return ResourceManager.GetString("PersonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purpose 的本地化字符串。
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Reimbursement 的本地化字符串。
        /// </summary>
        internal static string Reimbursement {
            get {
                return ResourceManager.GetString("Reimbursement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reject 的本地化字符串。
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rejected 的本地化字符串。
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approval Remark: 的本地化字符串。
        /// </summary>
        internal static string RemarkHistory {
            get {
                return ResourceManager.GetString("RemarkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark: 的本地化字符串。
        /// </summary>
        internal static string RemarkLabel {
            get {
                return ResourceManager.GetString("RemarkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save &amp; Apply 的本地化字符串。
        /// </summary>
        internal static string SaveApply {
            get {
                return ResourceManager.GetString("SaveApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Draft 的本地化字符串。
        /// </summary>
        internal static string SaveAsDraft {
            get {
                return ResourceManager.GetString("SaveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attached file(*): 的本地化字符串。
        /// </summary>
        internal static string ScanFile {
            get {
                return ResourceManager.GetString("ScanFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to view detail. 的本地化字符串。
        /// </summary>
        internal static string ScanningGridTitle {
            get {
                return ResourceManager.GetString("ScanningGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit 的本地化字符串。
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit Budget MTD(Used/All) 的本地化字符串。
        /// </summary>
        internal static string StationBudget {
            get {
                return ResourceManager.GetString("StationBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit Budget YTD(Used/All) 的本地化字符串。
        /// </summary>
        internal static string StationBudgetYTD {
            get {
                return ResourceManager.GetString("StationBudgetYTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unit: 的本地化字符串。
        /// </summary>
        internal static string StationLabel {
            get {
                return ResourceManager.GetString("StationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Date 的本地化字符串。
        /// </summary>
        internal static string SubmitDate {
            get {
                return ResourceManager.GetString("SubmitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submitted by 的本地化字符串。
        /// </summary>
        internal static string SubmitPerson {
            get {
                return ResourceManager.GetString("SubmitPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document: 的本地化字符串。
        /// </summary>
        internal static string SupportDocument {
            get {
                return ResourceManager.GetString("SupportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TableNo 的本地化字符串。
        /// </summary>
        internal static string TableNo {
            get {
                return ResourceManager.GetString("TableNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detination 的本地化字符串。
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To: 的本地化字符串。
        /// </summary>
        internal static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum: 的本地化字符串。
        /// </summary>
        internal static string TotalAmountLabel {
            get {
                return ResourceManager.GetString("TotalAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transportation 的本地化字符串。
        /// </summary>
        internal static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Travel Expense Apply 的本地化字符串。
        /// </summary>
        internal static string TravellingExpenseApply {
            get {
                return ResourceManager.GetString("TravellingExpenseApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Travel Report(*): 的本地化字符串。
        /// </summary>
        internal static string TravelReport {
            get {
                return ResourceManager.GetString("TravelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Un-Budget 的本地化字符串。
        /// </summary>
        internal static string UnBudget {
            get {
                return ResourceManager.GetString("UnBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vendor 的本地化字符串。
        /// </summary>
        internal static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for Approval 的本地化字符串。
        /// </summary>
        internal static string WaitingApprove {
            get {
                return ResourceManager.GetString("WaitingApprove", resourceCulture);
            }
        }
    }
}
